services:
  mysqldb:
    container_name: mysqlcontainerforapp
    image: mysql:8.0
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - $HOME/database:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: bd_spring_security_docker
      MYSQL_USER: admin
      MYSQL_PASSWORD: magadiflo
      MYSQL_ROOT_PASSWORD: magadiflo
      SERVICE_TAGS: prod
      SERVICE_NAME: mysqldb
    networks:
      - apinetwork

  networks:
    apinetwork:
      driver: bridge
